<?php

namespace Database\Seeders;

use App\Models\Escola;
use Illuminate\Database\Seeder;

class EscolasSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        $escolas =[
            [
                'id' => 1,
                'escola' => 'Adolfina Leonor Soares Dos Santos',
                'cie' => 402862,
                'regiao' => 'Centro',
                'bairro' => 'Sumare',
                'endereco' => 'Av. Siqueira Campos',
                'telefone' => '38812521',
                'created_at' => '2021-01-05 11:00:19',
                'updated_at' => '2021-01-05 11:00:19',
                'deleted_at' => NULL,
            ],
            [
                'id' => 2,
                'escola' => 'Adriana Aparecida Cassiano',
                'cie' => 5420,
                'regiao' => 'Sul',
                'bairro' => 'Pereque Mirim',
                'endereco' => 'R. Sao Roque',
                'telefone' => '38871449',
                'created_at' => '2021-01-05 11:00:19',
                'updated_at' => '2021-01-05 11:00:19',
                'deleted_at' => NULL,
            ],
            [
                'id' => 3,
                'escola' => 'Aida de Almeida Castro Grazioli',
                'cie' => 225940,
                'regiao' => 'Centro',
                'bairro' => 'Rio Do Ouro',
                'endereco' => 'Rua Francisco Ribeiro',
                'telefone' => '38822610',
                'created_at' => '2021-01-05 11:00:19',
                'updated_at' => '2021-01-05 11:00:19',
                'deleted_at' => NULL,
            ],
            [
                'id' => 4,
                'escola' => 'Alaor Xavier Junqueira',
                'cie' => 223098,
                'regiao' => 'Sul',
                'bairro' => 'Travessao',
                'endereco' => 'Rua Jose Ferreira Dos Santos',
                'telefone' => '38872612',
                'created_at' => '2021-01-05 11:00:19',
                'updated_at' => '2021-01-05 11:00:19',
                'deleted_at' => NULL,
            ],
            [
                'id' => 5,
                'escola' => 'Antonia Antunes Arouca',
                'cie' => 225939,
                'regiao' => 'Norte',
                'bairro' => 'Massagassu',
                'endereco' => 'Rua Italia Baffi Magni',
                'telefone' => '38843900',
                'created_at' => '2021-01-05 11:00:19',
                'updated_at' => '2021-01-05 11:00:19',
                'deleted_at' => NULL,
            ],
            [
                'id' => 6,
                'escola' => 'Antonia Ribeiro Da Silva',
                'cie' => 243449,
                'regiao' => 'Centro',
                'bairro' => 'Jardim California',
                'endereco' => 'Av. Cidade Alves Pereira',
                'telefone' => '38822286',
                'created_at' => '2021-01-05 11:00:19',
                'updated_at' => '2021-01-05 11:00:19',
                'deleted_at' => NULL,
            ],
            [
                'id' => 7,
                'escola' => 'Antonio De Freitas Avelar',
                'cie' => 447785,
                'regiao' => 'Centro',
                'bairro' => 'Estrela Dalva',
                'endereco' => 'Rua Joao Marcelo',
                'telefone' => '38822493',
                'created_at' => '2021-01-05 11:00:19',
                'updated_at' => '2021-01-05 11:00:19',
                'deleted_at' => NULL,
            ],
            [
                'id' => 8,
                'escola' => 'Aparecida Maria Pires De Meneses',
                'cie' => 2033,
                'regiao' => 'Norte',
                'bairro' => 'Olaria',
                'endereco' => 'Av. Marginal Ipiranga',
                'telefone' => '38838988',
                'created_at' => '2021-01-05 11:00:19',
                'updated_at' => '2021-01-05 11:00:19',
                'deleted_at' => NULL,
            ],
            [
                'id' => 9,
                'escola' => 'Benedito Inacio Soares',
                'cie' => 208334,
                'regiao' => 'Norte',
                'bairro' => 'Massagassu',
                'endereco' => 'Av Regina Margareth Passos',
                'telefone' => '38842450',
                'created_at' => '2021-01-05 11:00:19',
                'updated_at' => '2021-01-05 11:00:19',
                'deleted_at' => NULL,
            ],
            [
                'id' => 10,
                'escola' => 'Bernardo Ferreira Louzada',
                'cie' => 208346,
                'regiao' => 'Centro',
                'bairro' => 'Rio Do Ouro',
                'endereco' => 'Rua Horto Florestal',
                'telefone' => '38822221',
                'created_at' => '2021-01-05 11:00:19',
                'updated_at' => '2021-01-05 11:00:19',
                'deleted_at' => NULL,
            ],
            [
                'id' => 11,
                'escola' => 'Carlos Altero Ortega',
                'cie' => 225952,
                'regiao' => 'Sul',
                'bairro' => 'Morro Do Algodao',
                'endereco' => 'Rua Sete',
                'telefone' => '38873021',
                'created_at' => '2021-01-05 11:00:19',
                'updated_at' => '2021-01-05 11:00:19',
                'deleted_at' => NULL,
            ],
            [
                'id' => 12,
                'escola' => 'Carlos De Almeida Rodrigues Dr.',
                'cie' => 215077,
                'regiao' => 'Centro',
                'bairro' => 'Indaia',
                'endereco' => 'Av. Pernambuco',
                'telefone' => '38824679',
                'created_at' => '2021-01-05 11:00:19',
                'updated_at' => '2021-01-05 11:00:19',
                'deleted_at' => NULL,
            ],
            [
                'id' => 13,
                'escola' => 'CEI do Bairro Poiares',
                'cie' => 422423,
                'regiao' => 'Centro',
                'bairro' => 'Poiares',
                'endereco' => 'Av. Marechal Floriano Peixoto',
                'telefone' => '38876315',
                'created_at' => '2021-01-05 11:00:19',
                'updated_at' => '2021-01-05 11:00:19',
                'deleted_at' => NULL,
            ],
            [
                'id' => 14,
                'escola' => 'Celia Rocha Lobo',
                'cie' => 279626,
                'regiao' => 'Sul',
                'bairro' => 'Pereque Mirim',
                'endereco' => 'Rua Benedito Jacinto Do Prado',
                'telefone' => '38883311',
                'created_at' => '2021-01-05 11:00:19',
                'updated_at' => '2021-01-05 11:00:19',
                'deleted_at' => NULL,
            ],
            [
                'id' => 15,
                'escola' => 'Creche Santo Antonio',
                'cie' => 300603,
                'regiao' => 'Sul',
                'bairro' => 'Tinga',
                'endereco' => 'Rua Elvira Perpetua De Santana',
                'telefone' => '38873304',
                'created_at' => '2021-01-05 11:00:19',
                'updated_at' => '2021-01-05 11:00:19',
                'deleted_at' => NULL,
            ],
            [
                'id' => 16,
                'escola' => 'Edna Maria Nogueira Ferraz',
                'cie' => 6288,
                'regiao' => 'Sul',
                'bairro' => 'Pereque Mirim',
                'endereco' => 'Rua Benedito Fortunato',
                'telefone' => '38873014',
                'created_at' => '2021-01-05 11:00:19',
                'updated_at' => '2021-01-05 11:00:19',
                'deleted_at' => NULL,
            ],
            [
                'id' => 17,
                'escola' => 'Elisa Butschkau',
                'cie' => 273314,
                'regiao' => 'Sul',
                'bairro' => 'Barranco Alto',
                'endereco' => 'Avenida Manoel de Castro',
                'telefone' => '38871016',
                'created_at' => '2021-01-05 11:00:19',
                'updated_at' => '2021-01-05 11:00:19',
                'deleted_at' => NULL,
            ],
            [
                'id' => 18,
                'escola' => 'Ester Nunes De Souza',
                'cie' => 499559,
                'regiao' => 'Norte',
                'bairro' => 'Sertao Dos Tourinhos',
                'endereco' => 'Rua Manoel Francisco Ricardo',
                'telefone' => '38841655',
                'created_at' => '2021-01-05 11:00:19',
                'updated_at' => '2021-01-05 11:00:19',
                'deleted_at' => NULL,
            ],
            [
                'id' => 19,
                'escola' => 'Euclydes Ferreira',
                'cie' => 499560,
                'regiao' => 'Sul',
                'bairro' => 'Pereque Mirim',
                'endereco' => 'Av. Jose Geraldo Fernandes Da Silva Filho',
                'telefone' => '38851802',
                'created_at' => '2021-01-05 11:00:19',
                'updated_at' => '2021-01-05 11:00:19',
                'deleted_at' => NULL,
            ],
            [
                'id' => 20,
                'escola' => 'Francisco Assis De Carvalho',
                'cie' => 225988,
                'regiao' => 'Sul',
                'bairro' => 'Pereque Mirim',
                'endereco' => 'Av. Jose Geraldo Fernandes Da Silva Filho',
                'telefone' => '38851801',
                'created_at' => '2021-01-05 11:00:19',
                'updated_at' => '2021-01-05 11:00:19',
                'deleted_at' => NULL,
            ],
            [
                'id' => 21,
                'escola' => 'Geraldo De Lima',
                'cie' => 273302,
                'regiao' => 'Sul',
                'bairro' => 'Pereque Mirim',
                'endereco' => 'Av. Pedro Goncalves',
                'telefone' => '38874322',
                'created_at' => '2021-01-05 11:00:19',
                'updated_at' => '2021-01-05 11:00:19',
                'deleted_at' => NULL,
            ],
            [
                'id' => 22,
                'escola' => 'Honorina Pacheco Correa',
                'cie' => 5336,
                'regiao' => 'Centro',
                'bairro' => 'Rio Do Ouro',
                'endereco' => 'Av. Americo Thimoteo Do Rosario',
                'telefone' => '38835577',
                'created_at' => '2021-01-05 11:00:19',
                'updated_at' => '2021-01-05 11:00:19',
                'deleted_at' => NULL,
            ],
            [
                'id' => 23,
                'escola' => 'Jane Urbano Focesi',
                'cie' => 215089,
                'regiao' => 'Sul',
                'bairro' => 'Pereque Mirim',
                'endereco' => 'R. Sao Roque',
                'telefone' => '38871514',
                'created_at' => '2021-01-05 11:00:19',
                'updated_at' => '2021-01-05 11:00:19',
                'deleted_at' => NULL,
            ],
            [
                'id' => 24,
                'escola' => 'Joao Baptista Gardelin',
                'cie' => 200359,
                'regiao' => 'Centro',
                'bairro' => 'Poiares',
                'endereco' => 'Rua Joaquim Jose Da Silva Xavier',
                'telefone' => '38873101',
                'created_at' => '2021-01-05 11:00:19',
                'updated_at' => '2021-01-05 11:00:19',
                'deleted_at' => NULL,
            ],
            [
                'id' => 25,
                'escola' => 'Joao Benedito Marcondes',
                'cie' => 383636,
                'regiao' => 'Sul',
                'bairro' => 'Baranco Alto',
                'endereco' => 'Rua Jose Domingos Cardoso',
                'telefone' => '38874291',
                'created_at' => '2021-01-05 11:00:19',
                'updated_at' => '2021-01-05 11:00:19',
                'deleted_at' => NULL,
            ],
            [
                'id' => 26,
                'escola' => 'Joao Lino Da Cruz',
                'cie' => 208358,
                'regiao' => 'Sul',
                'bairro' => 'Baranco Alto',
                'endereco' => 'Rua Luiz Jacinto Da Silva',
                'telefone' => '38882865',
                'created_at' => '2021-01-05 11:00:19',
                'updated_at' => '2021-01-05 11:00:19',
                'deleted_at' => NULL,
            ],
            [
                'id' => 27,
                'escola' => 'Joao Thimoteo Do Rosario',
                'cie' => 225997,
                'regiao' => 'Norte',
                'bairro' => 'Cantagalo',
                'endereco' => 'Estrada Do Cantagalo',
                'telefone' => '38890278',
                'created_at' => '2021-01-05 11:00:19',
                'updated_at' => '2021-01-05 11:00:19',
                'deleted_at' => NULL,
            ],
            [
                'id' => 28,
                'escola' => 'Jorge Passos',
                'cie' => 22226,
                'regiao' => 'Centro',
                'bairro' => 'Jaraguazinho',
                'endereco' => 'Rua Oziel Egidio De Faria',
                'telefone' => '38824395',
                'created_at' => '2021-01-05 11:00:19',
                'updated_at' => '2021-01-05 11:00:19',
                'deleted_at' => NULL,
            ],
            [
                'id' => 29,
                'escola' => 'Leonor Mendes De Barros',
                'cie' => 222324,
                'regiao' => 'Sul',
                'bairro' => 'Travessao',
                'endereco' => 'Rua Joao Carlos Balio',
                'telefone' => '38876108',
                'created_at' => '2021-01-05 11:00:19',
                'updated_at' => '2021-01-05 11:00:19',
                'deleted_at' => NULL,
            ],
            [
                'id' => 30,
                'escola' => 'Lucio Jacinto Dos Santos',
                'cie' => 243450,
                'regiao' => 'Centro',
                'bairro' => 'Tinga',
                'endereco' => 'Rua Denilza Sebastiana Santos',
                'telefone' => '38834533',
                'created_at' => '2021-01-05 11:00:19',
                'updated_at' => '2021-01-05 11:00:19',
                'deleted_at' => NULL,
            ],
            [
                'id' => 31,
                'escola' => 'Luiz Ribeiro Muniz',
                'cie' => 565817,
                'regiao' => 'Centro',
                'bairro' => 'Martim De Sa',
                'endereco' => 'Rua Analandia',
                'telefone' => '38825698',
                'created_at' => '2021-01-05 11:00:19',
                'updated_at' => '2021-01-05 11:00:19',
                'deleted_at' => NULL,
            ],
            [
                'id' => 32,
                'escola' => 'Luiz Silvar Do Prado',
                'cie' => 495037,
                'regiao' => 'Norte',
                'bairro' => 'Casa Branca',
                'endereco' => 'Rua Jose Pedro De Oliveira Barbosa',
                'telefone' => '38869931',
                'created_at' => '2021-01-05 11:00:19',
                'updated_at' => '2021-01-05 11:00:19',
                'deleted_at' => NULL,
            ],
            [
                'id' => 33,
                'escola' => 'Maria Aparecida De Carvalho',
                'cie' => 225903,
                'regiao' => 'Centro',
                'bairro' => 'Tinga',
                'endereco' => 'Av. Marechal Deodoro Da Fonseca',
                'telefone' => '38862050',
                'created_at' => '2021-01-05 11:00:19',
                'updated_at' => '2021-01-05 11:00:19',
                'deleted_at' => NULL,
            ],
            [
                'id' => 34,
                'escola' => 'Maria Aparecida Ujio',
                'cie' => 22299,
                'regiao' => 'Sul',
                'bairro' => 'Porto Novo',
                'endereco' => 'Av. Ezequiel Da Silva Barreto',
                'telefone' => '38873836',
                'created_at' => '2021-01-05 11:00:19',
                'updated_at' => '2021-01-05 11:00:19',
                'deleted_at' => NULL,
            ],
            [
                'id' => 35,
                'escola' => 'Maria Carlita Saraiva Guedes',
                'cie' => 201777,
                'regiao' => 'Sul',
                'bairro' => 'Morro Do Algodao',
                'endereco' => 'Travessa Cinco',
                'telefone' => '38883223',
                'created_at' => '2021-01-05 11:00:19',
                'updated_at' => '2021-01-05 11:00:19',
                'deleted_at' => NULL,
            ],
            [
                'id' => 36,
                'escola' => 'Maria De Lourdes Lucarelli Perez',
                'cie' => 495025,
                'regiao' => 'Centro',
                'bairro' => 'Indaia',
                'endereco' => 'Av. Santa Catarina',
                'telefone' => '38877822',
                'created_at' => '2021-01-05 11:00:19',
                'updated_at' => '2021-01-05 11:00:19',
                'deleted_at' => NULL,
            ],
            [
                'id' => 37,
                'escola' => 'Maria Elma Mansano',
                'cie' => 565748,
                'regiao' => 'Centro',
                'bairro' => 'Tinga',
                'endereco' => 'Av. Marechal Deodoro Da Fonseca',
                'telefone' => '38862054',
                'created_at' => '2021-01-05 11:00:19',
                'updated_at' => '2021-01-05 11:00:19',
                'deleted_at' => NULL,
            ],
            [
                'id' => 38,
                'escola' => 'Maria Eugenia Aranha Chodounsky',
                'cie' => 435879,
                'regiao' => 'Norte',
                'bairro' => 'Casa Branca',
                'endereco' => 'Rua Jose Pedro De Oliveira Barbosa',
                'telefone' => '38869932',
                'created_at' => '2021-01-05 11:00:19',
                'updated_at' => '2021-01-05 11:00:19',
                'deleted_at' => NULL,
            ],
            [
                'id' => 39,
                'escola' => 'Maria Moraes De Oliveira',
                'cie' => 569537,
                'regiao' => 'Centro',
                'bairro' => 'Jardim Gaivotas',
                'endereco' => 'Rua Pica Pau',
                'telefone' => '38877462',
                'created_at' => '2021-01-05 11:00:19',
                'updated_at' => '2021-01-05 11:00:19',
                'deleted_at' => NULL,
            ],
            [
                'id' => 40,
                'escola' => 'Maria Onicie Dias Pereira',
                'cie' => 225976,
                'regiao' => 'Centro',
                'bairro' => 'Jaraguazinho',
                'endereco' => 'Rua Jose Neder',
                'telefone' => '38878087',
                'created_at' => '2021-01-05 11:00:19',
                'updated_at' => '2021-01-05 11:00:19',
                'deleted_at' => NULL,
            ],
            [
                'id' => 41,
                'escola' => 'Maria Thereza De Souza Castro',
                'cie' => 208361,
                'regiao' => 'Norte',
                'bairro' => 'Getuba',
                'endereco' => 'Rua Seishi Yoshimoto',
                'telefone' => '38842921',
                'created_at' => '2021-01-05 11:00:19',
                'updated_at' => '2021-01-05 11:00:19',
                'deleted_at' => NULL,
            ],
            [
                'id' => 42,
                'escola' => 'Masako Sone',
                'cie' => 810642,
                'regiao' => 'Sul',
                'bairro' => 'Pegorelli',
                'endereco' => 'Rua Abra De Dentro',
                'telefone' => '38872444',
                'created_at' => '2021-01-05 11:00:19',
                'updated_at' => '2021-01-05 11:00:19',
                'deleted_at' => NULL,
            ],
            [
                'id' => 43,
                'escola' => 'Meimei',
                'cie' => 273351,
                'regiao' => 'Centro',
                'bairro' => 'Tinga',
                'endereco' => 'Rua Odete Machado Pinto',
                'telefone' => '38834648',
                'created_at' => '2021-01-05 11:00:19',
                'updated_at' => '2021-01-05 11:00:19',
                'deleted_at' => NULL,
            ],
            [
                'id' => 44,
                'escola' => 'Messias Mendes De Souza',
                'cie' => 225964,
                'regiao' => 'Centro',
                'bairro' => 'Ipiranga',
                'endereco' => 'Av. Brasil',
                'telefone' => '38839788',
                'created_at' => '2021-01-05 11:00:19',
                'updated_at' => '2021-01-05 11:00:19',
                'deleted_at' => NULL,
            ],
            [
                'id' => 45,
                'escola' => 'Oswaldo Ferreira',
                'cie' => 226002,
                'regiao' => 'Norte',
                'bairro' => 'Casa Branca',
                'endereco' => 'Rua Jose Pedro De Oliveira Barbosa',
                'telefone' => '38821067',
                'created_at' => '2021-01-05 11:00:19',
                'updated_at' => '2021-01-05 11:00:19',
                'deleted_at' => NULL,
            ],
            [
                'id' => 46,
                'escola' => 'Pedro Joao De Oliveira',
                'cie' => 78086,
                'regiao' => 'Norte',
                'bairro' => 'Tabatinga',
                'endereco' => 'Rua Benedito Serrado',
                'telefone' => '38842091',
                'created_at' => '2021-01-05 11:00:19',
                'updated_at' => '2021-01-05 11:00:19',
                'deleted_at' => NULL,
            ],
            [
                'id' => 47,
                'escola' => 'Regina Celia Santos Chapira Blaustein',
                'cie' => 375172,
                'regiao' => 'Sul',
                'bairro' => 'Travessao',
                'endereco' => 'Rua Jacupiranga',
                'telefone' => '38876422',
                'created_at' => '2021-01-05 11:00:19',
                'updated_at' => '2021-01-05 11:00:19',
                'deleted_at' => NULL,
            ],
            [
                'id' => 48,
                'escola' => 'Ricardo Luques Sammarco Serra',
                'cie' => 78074,
                'regiao' => 'Sul',
                'bairro' => 'Praia Das Palmeiras',
                'endereco' => 'Rua Aldo Marcucci',
                'telefone' => '38884186',
                'created_at' => '2021-01-05 11:00:19',
                'updated_at' => '2021-01-05 11:00:19',
                'deleted_at' => NULL,
            ],
            [
                'id' => 49,
                'escola' => 'Santina Nardi Marques',
                'cie' => 435983,
                'regiao' => 'Centro',
                'bairro' => 'Estrela Dalva',
                'endereco' => 'Rua Antonio Nardi',
                'telefone' => '38833477',
                'created_at' => '2021-01-05 11:00:19',
                'updated_at' => '2021-01-05 11:00:19',
                'deleted_at' => NULL,
            ],
            [
                'id' => 50,
                'escola' => 'Severino Vitoriano Dos Santos',
                'cie' => 807679,
                'regiao' => 'Centro',
                'bairro' => 'Jardim Das Gaivotas',
                'endereco' => 'Av. Cardeal',
                'telefone' => '38873047',
                'created_at' => '2021-01-05 11:00:19',
                'updated_at' => '2021-01-05 11:00:19',
                'deleted_at' => NULL,
            ],
            [
                'id' => 51,
                'escola' => 'Telma Do Amarante Veiga Santos',
                'cie' => 442628,
                'regiao' => 'Centro',
                'bairro' => 'Tinga',
                'endereco' => 'Rua Antonio Dos Santos',
                'telefone' => '38826090',
                'created_at' => '2021-01-05 11:00:19',
                'updated_at' => '2021-01-05 11:00:19',
                'deleted_at' => NULL,
            ],
            [
                'id' => 52,
                'escola' => 'Thereza Yanesse Schmidt Cardozo',
                'cie' => 451861,
                'regiao' => 'Sul',
                'bairro' => 'Porto Novo',
                'endereco' => 'Av. Ezequiel Da Silva Barreto',
                'telefone' => '38871565',
                'created_at' => '2021-01-05 11:00:19',
                'updated_at' => '2021-01-05 11:00:19',
                'deleted_at' => NULL,
            ],
            [
                'id' => 53,
                'escola' => 'Vera Da Silva Santos',
                'cie' => 5780,
                'regiao' => 'Norte',
                'bairro' => 'Getuba',
                'endereco' => 'Av. Azaleias',
                'telefone' => '38893535',
                'created_at' => '2021-01-05 11:00:19',
                'updated_at' => '2021-01-05 11:00:19',
                'deleted_at' => NULL,
            ],
            [
                'id' => 54,
                'escola' => 'Yasutada Nasu',
                'cie' => 212489,
                'regiao' => 'Sul',
                'bairro' => 'Pereque Mirim',
                'endereco' => 'R. Pedro Goncalves Leite',
                'telefone' => '38874322',
                'created_at' => '2021-01-05 11:00:19',
                'updated_at' => '2021-01-05 11:00:19',
                'deleted_at' => NULL,
            ],
            [
                'id' => 55,
                'escola' => 'Seduc',
                'cie' => 1,
                'regiao' => 'Centro',
                'bairro' => 'Indaiá',
                'endereco' => 'Av. Rio de Janeiro 860',
                'telefone' => '38977000',
                'created_at' => '2021-02-25 23:04:54',
                'updated_at' => '2021-02-25 23:04:54',
                'deleted_at' => NULL,
            ],
            [
                'id' => 56,
                'escola' => 'CIASE - Governador Adhemar Pereira de Barros',
                'cie' => 1,
                'regiao' => 'Sul',
                'bairro' => 'Travessão',
                'endereco' => 'Av. Rio de Janeiro 860',
                'telefone' => '38977000',
                'created_at' => '2021-02-25 23:04:54',
                'updated_at' => '2021-02-25 23:04:54',
                'deleted_at' => NULL,
            ],
            [
                'id' => 57,
                'escola' => 'CIASE - Wilson Francisco Valente',
                'cie' => 1,
                'regiao' => 'Centro',
                'bairro' => 'Sumaré',
                'endereco' => 'Av. Rio de Janeiro 860',
                'telefone' => '38977000',
                'created_at' => '2021-02-25 23:04:54',
                'updated_at' => '2021-02-25 23:04:54',
                'deleted_at' => NULL,
            ],
            [
                'id' => 58,
                'escola' => 'CRIE Casa Branca',
                'cie' => 1,
                'regiao' => 'Norte',
                'bairro' => 'Casa branca',
                'endereco' => 'Av. Rio de Janeiro 860',
                'telefone' => '38977000',
                'created_at' => '2021-02-25 23:04:54',
                'updated_at' => '2021-02-25 23:04:54',
                'deleted_at' => NULL,
            ],
            [
                'id' => 59,
                'escola' => 'CRIE Pereque',
                'cie' => 1,
                'regiao' => 'Sul',
                'bairro' => 'Perequê',
                'endereco' => 'Av. Rio de Janeiro 860',
                'telefone' => '38977000',
                'created_at' => '2021-02-25 23:04:54',
                'updated_at' => '2021-02-25 23:04:54',
                'deleted_at' => NULL,
            ],
            [
                'id' => 60,
                'escola' => 'CRIE Tinga',
                'cie' => 1,
                'regiao' => 'Centro',
                'bairro' => 'Tinga',
                'endereco' => 'Av. Rio de Janeiro 860',
                'telefone' => '38977000',
                'created_at' => '2021-02-25 23:04:54',
                'updated_at' => '2021-02-25 23:04:54',
                'deleted_at' => NULL,
            ],
            [
                'id' => 61,
                'escola' => 'UNIVESP',
                'cie' => 1,
                'regiao' => 'Centro',
                'bairro' => 'Estrela Dalva',
                'endereco' => 'Av. Rio de Janeiro 860',
                'telefone' => '38977000',
                'created_at' => '2021-02-25 23:04:54',
                'updated_at' => '2021-02-25 23:04:54',
                'deleted_at' => NULL,
            ],
        ];
        Escola::insert($escolas);
    }
}
